### ISSUE TITLE
database support for Virtual Shop

### ISSUE THREAD

**Issue by NakiriAyamesuki** [nulli0n/ExcellentShop-spigot#1]
Is there database support for the buy/sell quantity limits and cooldown of Virtual Shop items?it didn't work on the bungee server

I set the same item (limit sell 1000, cooldown 86400s) in a different server in Bungee, but with the database enabled, the limit for each server is independent

**Comment by nulli0n** [comment]
Will be supported soon

**Comment by nulli0n** [comment]
Done!
