### ISSUE TITLE
Can't sell items to auction house

### ISSUE THREAD

**Issue by Legoman99573** [nulli0n/ExcellentShop-spigot#13]
Expected Behavior:
Be able to list the item on Auction House

Behavior Instead:
``You can not add more than 0 active listings on auction!``
![javaw_EoTl4FSk5V](https://github.com/nulli0n/ExcellentShop-spigot/assets/7460704/cf697201-41f2-4170-8350-44bd09b2dfed)

Info from ``/excellentshop about``
![image](https://github.com/nulli0n/ExcellentShop-spigot/assets/7460704/d8c7ea8c-fd76-40c6-8c23-7c467ad1b6b6)

**Comment by nulli0n** [comment]
Redownload please, it have been fixed.
