### ISSUE TITLE
Error when trying to create a rotating shop

### ISSUE THREAD

**Issue by DxrkCxt** [nulli0n/ExcellentShop-spigot#23]
https://paste.gg/p/anonymous/ac22ed1497de4022805ac87628af943a
![image](https://github.com/nulli0n/ExcellentShop-spigot/assets/124828932/96fa1531-af92-40df-92ae-2409313dce89)
![image](https://github.com/nulli0n/ExcellentShop-spigot/assets/124828932/b8ca0b08-a4c9-4a62-81dc-4b04b3e6eff2)

**Comment by nulli0n** [comment]
Use 4.8.1 plugin version.
