### ISSUE TITLE
Message issue

### ISSUE THREAD

**Issue by WarnDa** [nulli0n/ExcellentShop-spigot#31]
In the messages_en.yml, in the InfiniteStorage section, the message
`Success: <lgray>You withdraw <lgreen>x%amount% %item%</lgreen> from shop storage!</lgray>`
will display the total storage amount instead of the number of item you succesfully removed.

How to reproduce : 
- go to the storage
- press the "withdraw all" key
- it will write "you withdraw XXX items" and will show the total storage quantity

**Comment by nulli0n** [comment]
Fixed in v4.11.4
