### ISSUE TITLE
Custom model items cannot be sold with one click

### ISSUE THREAD

**Issue by CCjun6** [nulli0n/ExcellentShop-spigot#34]
![image](https://github.com/user-attachments/assets/f450d81d-4003-4f5d-a65c-3f1322fa290a)
One-click sell only works for default items. Custom model items cannot be sold with one click; you must find the corresponding item and then click to sell.
Is this a bug or is it designed this way?

**Comment by nulli0n** [comment]
Should be fixed in v4.11.4
