### ISSUE TITLE
Custom model items still cannot be sold

### ISSUE THREAD

**Issue by CCjun6** [nulli0n/ExcellentShop-spigot#37]
After updating to version 4.11.4, custom model items still cannot be sold. In version 4.11.3, it was possible to sell them by pressing the F key, but now the F key has also stopped working. Please fix this.

![image](https://github.com/user-attachments/assets/3daf38d2-4e15-4f70-8bc2-20431f2e4931)
![image](https://github.com/user-attachments/assets/865987a0-bc24-49ed-bef4-a994ecb3f90a)

**Comment by nulli0n** [comment]
Try v4.11.6

**Comment by CCjun6** [comment]
> Try v4.11.6

The error still persists after testing.
