### ISSUE TITLE
Unable to Sell Custom Items

### ISSUE THREAD

**Issue by CCjun6** [nulli0n/ExcellentShop-spigot#38]
Hi, I'm here to report another issue. This time, I'm using version 4.11.5 and I've noticed that players are unable to sell custom items. Additionally, the "Quick Sell" button still doesn't work, and pressing the "F" key to sell items doesn't function either. I've attached a video this time so you can take a look. I hope this can be fixed.
[

https://github.com/user-attachments/assets/720c0483-bf1f-4d0a-8310-043d2106a89e

](url)

**Comment by nulli0n** [comment]
Try v4.11.6

**Comment by CCjun6** [comment]
The error still persists after testing.

**Comment by nulli0n** [comment]
From what plugin these items are from?

**Comment by CCjun6** [comment]
> 这些项目来自哪个插件？

itemadder

**Comment by CCjun6** [comment]
> itemadder

itemadder

**Comment by CCjun6** [comment]
> From what plugin these items are from?



> From what plugin these items are from?

itemsadder

**Comment by CCjun6** [comment]
> From what plugin these items are from?

I would like to know if there is an estimated time for fixing the two issues I reported.
