### ISSUE TITLE
Display issue on newer version

### ISSUE THREAD

**Issue by WarnDa** [nulli0n/ExcellentShop-spigot#39]
Since v4.11.5 it oftens show twice the item on the shop.
I'm using the default display system (using protocollib) on 1.20.4 paper

The issue wasn't here before en v4.11.2
![image](https://github.com/user-attachments/assets/5fbae9b6-d043-45b6-bf08-970b78c659b7)

**Comment by WarnDa** [comment]
Edit : 
If you go near a shop, then go far away and come near again, you'll see twice the display item

**Comment by nulli0n** [comment]
Should be fixed in v4.11.6

**Comment by WarnDa** [comment]
It's okay on my tests, will reopen if an error occur again !
thanks
