### ISSUE TITLE
[Suggestion] Add coordinate/owner for transaction

### ISSUE THREAD

**Issue by WarnDa** [nulli0n/ExcellentShop-spigot#41]
For chestshop, add in logs the shop URL and the shop owner, because it's hard to find out who is the owner and the shop if multiple player use the same name for the shops

**Comment by nulli0n** [comment]
Add to transaction log format: `[%shop_location_x%, %shop_location_y%, %shop_location_z% in %shop_location_world%, owned by %shop_owner%]`
