### ISSUE TITLE
After updating to the latest version, variables are having issues

### ISSUE THREAD

**Issue by CCjun6** [nulli0n/ExcellentShop-spigot#42]
![image](https://github.com/user-attachments/assets/4edceceb-c4aa-406f-a752-1f9b869e0f71)
![image](https://github.com/user-attachments/assets/4a7edbdb-de86-48e5-a5f3-757e8f5baa36)

They will all have a currency format

**Comment by nulli0n** [comment]
Fixed in v4.13.0
