### ISSUE TITLE
doesn't work on Paper-1.19.2-build307

### ISSUE THREAD

**Issue by avalonworldw** [nulli0n/ExcellentShop-spigot#7]
It doesn't work on Paper-1.19.2-build307. I can't find the exclusive download address of paper, and I don't have the ability to build it. But I bought this plug-in at spigotmc. How should I operate it?

**Comment by nulli0n** [comment]
The plugin works fine on 1.19.2. Make sure you have the latest release of NexEngine

**Comment by XyRealm** [comment]
The reason has been found. Do not use the modified vault of the cmi author
